### ISSUE TITLE
Gitの使用にあたって遵守すべきルール

### ISSUE THREAD

**Issue by WakishiDeer** [OH-DEER-NO-BEER/sakata-shoten-common#10]
https://qiita.com/y-okudera/items/0b57830d2f56d1d51692
**Gitのブランチモデル**について，上記（もしくはそれ以外）のうちどれを採用するか？

**Comment by yokoro13** [comment]
自分はCase3派

**Comment by WakishiDeer** [comment]
@yokoro13 わかりました．ありがとうございます．
では {main, develop, feature} ブランチでいきましょうか．
